### ISSUE TITLE
Import URL on click bug

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-importer#10]
Currently imports URL of image

**Comment by giucu91** [comment]
La Photoblocks nu ia si open in new tab

**Comment by giucu91** [comment]
Nici la eenvira

**Comment by giucu91** [comment]
La nextgen nu ia title / alt / caption

**Comment by razvanaldea89** [comment]
@giucu91 testat acum pentru nextgen si imi ia title / alt / caption.  Imi poti spune pasii?

**Comment by andyluak** [comment]
Imi ia si title si caption si nu se intampla nici open in new tab .
