### ISSUE TITLE
Revizuit

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-importer#15]
1. De adus cu ajax galeriile pe pagina peentru viteza
2. Scos checkul pentru PRO
3. De facut un singur script js in loc de 5

**Comment by giucu91** [comment]
@razvanaldea89 am putea comasa acestee functii : 

modulaWPCoreImporter.init();
modulaPhotoblocksImporter.init();
modulaFinalTilesImporter.init();
modulaNextgenImporter.init();
modulaEnviraImporter.init();

in una singura ?

**Comment by razvanaldea89** [comment]
Da, teoretic am putea sa facem o singura functie pentru toate, in mare sunt identice.

**Comment by andyluak** [comment]
The galleries migrate with ajax . No check for pro . One js script . No errors found on console .
