### ISSUE TITLE
Final Tiles Gallery option not displayed in Gallery source selection

### ISSUE THREAD

**Issue by andrei-l-cristea** [MachoThemes/modula-importer#17]
Although I have the plugin installed, enabled and created a gallery for it, the Final Tiles Gallery option is not available in the Gallery Source selection field.

**Comment by andrei-l-cristea** [comment]
The Core WP Galleries are also not listed.

**Comment by razvanaldea89** [comment]
A fix has been issued - https://github.com/MachoThemes/modula-importer/commit/c37ccd4624c812112739bd5b317479d0997740e6
Seems like there was a problem with final tiles tables, some servers save them lowercase and some save them as the plugin commands.

**Comment by andrei-l-cristea** [comment]
This has been fixed.
