### ISSUE TITLE
Naming from Importer -> Migrate

### ISSUE THREAD

**Issue by andrei-l-cristea** [MachoThemes/modula-importer#19]
Since we are using Migrate everywhere I think it would sound better with Modula Migrate

**Comment by razvanaldea89** [comment]
Changed plugin name, will change plugin files tomorrow

**Comment by cristianraiber** [comment]
Don't worry about this. The code will get merged into Modula Lite anyways. This won't be released as a standalone plugin. cc @giucu91 ?
