### ISSUE TITLE
WP Core Gallery number of images

### ISSUE THREAD

**Issue by andrei-l-cristea** [MachoThemes/modula-importer#20]
Although I have two galleries in my page with 3 images each, when accessing the Migrate section for this source the number of images is still 0.
![image](https://user-images.githubusercontent.com/53428716/73456068-e3318a80-4379-11ea-9a6b-5e72c4e26f7d.png)

**Comment by andyluak** [comment]
Added 5 galleries , waas able to import all of them with no issues .
