### ISSUE TITLE
Imported galleries check

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-importer#3]
Save imported galleries in modula_importer option based on gallery plugin. Cases when 2 ore more galleries have the same id can happen ( separate tables but same id ).

**Comment by giucu91** [comment]
@cristianraiber  @razvanaldea89  I think here we need to tell people that a certain gallery is already imported. What you think ?

**Comment by razvanaldea89** [comment]
There is already a function that tells you that the gallery has been imported.

**Comment by andrei-l-cristea** [comment]
Yes, but you can import the same gallery again and again... wouldn't it be better if the gallery was already imported to stop the duplicate migration. For example if an user has 10 galleries and selects only 5, then in his next migration imports all of them, this will create 5 duplicates.

**Comment by razvanaldea89** [comment]
We can do that, but we will limit the user in migrating only 1 time. In case he wants to import again/make a double he won't be allowed. Although, Modula has a clone option. Can't think of any good reason an user would want to migrate multiple times same gallery. Will apply this fix
