### ISSUE TITLE
Adaugat meta pentru galeriile importate

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-importer#30]
Ar trebui sa adaugam in meta la galerie in loc de un option pentru toate.

Scenariu :
Daca am importat o galerie si apoi am sters.o nu o mai pot importa niciodata asa daca e in meta o sa meaerga importata.

**Comment by andyluak** [comment]
Tested with finaltiles , photoblocks and nextgen and i was able to import , delete galeries and impor them again .
