### ISSUE TITLE
Photoblocks

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-importer#31]
Aici galeria ar trebui sa fie de tip custom grid si sa transformam dintr.o galerie de 4 coloane in 12 coloane.

**Comment by andyluak** [comment]
Uploaded from photoblocks . Imports all the images + in modula reflects a 12 grid custom grid layout .

**Comment by giucu91** [comment]
PhotoBlocks :
![image](https://user-images.githubusercontent.com/7580330/75882398-c29d9a00-5e29-11ea-85c7-de22263993e3.png)

Modula after Import : 
![image](https://user-images.githubusercontent.com/7580330/75882432-d5b06a00-5e29-11ea-9564-dbd32b47acec.png)

How it should be : 
![image](https://user-images.githubusercontent.com/7580330/75882556-14debb00-5e2a-11ea-9a15-fc0b085f5f40.png)

1x1 Photoblock square = 3x3 Modula Square.
