### ISSUE TITLE
When importing galleries, the images get duplicated in the WP Media

### ISSUE THREAD

**Issue by andyluak** [MachoThemes/modula-importer#6]
Importer Test with PhotoBlocks :
-When importing images, they get duplicated in the WP Media even if they already exist .
	-Create a gallery in PhotoBlocks using images from WP Media
	-Import gallery 
	-After importing , the images get duplicated in the WP Media Folder
-After every import , it will duplicate the images in the Media Folder 

Importer Test with FinalTiles :
-When importing images, they get duplicated in the WP Media .
	-Create a gallery in PhotoBlocks using images from WP Media
	-Import gallery 
	-After importing , the images get duplicated in the WP Media Folder
-After every import , it will duplicate the images in the Media Folder

**Comment by razvanaldea89** [comment]
NextGEN still needs to check when images are from Media Library and not imported in own folder.

**Comment by andrei-l-cristea** [comment]
Just tested with Photoblocks and the images are not duplicated. Waiting for the fix for Final Tiles Gallery so I can test with that as well.

**Comment by andrei-l-cristea** [comment]
Tested this with NextGen and duplicates are created when importing the the gallery.

**Comment by giucu91** [comment]
Cu NextGen nu mai face duplicat dar nu pot inca testa Final Tiles

**Comment by razvanaldea89** [comment]
@giucu91  de ce nu poti testa Final Tiles?

**Comment by andyluak** [comment]
Tested with NextGen , Photoblocks and FinalTiles and the issues seemn to be resolved .
